=== djstein/eeh_pattern/EEH_Pattern/null/schema/ExceptionCatalogMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:exc="urn:com.ibm.mq.exc" targetNamespace="urn:com.ibm.mq.exc">
	<xsd:element name="ExceptionCatalog" type="exc:Typ.ExceptionCatalog">
		<xsd:key name="excName">
		  <xsd:selector xpath="Exception"/>
		  <xsd:field xpath="@name"/>
		</xsd:key>
	</xsd:element>
	
	<xsd:complexType name="Typ.ExceptionCatalog">
		<xsd:sequence>
			<xsd:element name="Exception" type="exc:Typ.Exception" minOccurs="1" maxOccurs="unbounded">
				<xsd:key name="excParm">
				  <xsd:selector xpath="Parameter"/>
				  <xsd:field xpath="@name"/>
				</xsd:key>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="language" type="xsd:string" use="required"/>
       	<xsd:attribute name="descr" type="xsd:string" use="required"/>
    </xsd:complexType>
	
	<xsd:complexType name="Typ.Exception">
		<xsd:sequence>
			<xsd:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:string"/>
					<xsd:attribute name="member" type="xsd:string"/>
					<xsd:attribute name="type">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="method"/>
								<xsd:enumeration value="field"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="class" type="xsd:string"/>
	</xsd:complexType>
	
</xsd:schema>

=== djstein/eeh_pattern/EEH_Pattern/master/exccat/ExcCat.EEH_Master_JavaMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

 Licensed Materials - Property of IBM
 (C) Copyright IBM Corp. 2009 All Rights Reserved.
 US Government Users Restricted Rights - Use, duplication or
 disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

 Created January 2008, 2012

-->

<exc:ExceptionCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="urn:com.ibm.mq.exc ExceptionCatalogMap.xsd"
					xmlns:exc="urn:com.ibm.mq.exc"

		language="Java"
		descr="Java Master Exception Mapping file.">

	<!-- *************************************************** 
	     EXCEPTION CATAGORY = 00 => Not found: TODO
	     *************************************************** -->


	<!-- *************************************************** 
	     EXCEPTION CATAGORY = 01 => Operating System Related 
	     *************************************************** -->
	
	<Exception name="FILE_NOT_FOUND" class="java.io.FileNotFoundException">
		<Parameter name="Path" member="getPath" type="method"/>
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>	
	</Exception>

	<Exception name="IO" class="java.io.IOException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>

	<Exception name="CLASS_UNDEF" class="java.lang.ClassNotFoundException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>

	<Exception name="CLASS_INSTANTIATION_ERROR" class="java.lang.InstantiationException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>



	<!-- ****************************************** 
	     EXCEPTION CATAGORY = 02 => Network Related
	     ****************************************** -->


	<!-- *******************************************
	     EXCEPTION CATAGORY = 03 => Security Related
	     ******************************************* -->

	<Exception name="CIPHER_KEY_INVALID" class="java.security.InvalidKeyException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>

	<Exception name="CIPHER_BLOCK_SIZE" class="java.crypto.IllegalBlockSizeException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>


	<!-- *************************************************
	     EXCEPTION CATAGORY = 04 => Data Integrity Related
	     ************************************************* -->

	<Exception name="XML_VALIDATION" class="org.xml.sax.SAXException">
		<Parameter name="SystemId" member="getSystemId" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
		<Parameter name="ColumnNo" member="getColumnNumber" type="method"/>
		<Parameter name="LineNo" member="getLineNumber" type="method"/>
		<Parameter name="PublicId" member="getPublicId" type="method"/>
	</Exception>

	<Exception name="MALFORMED_URL" class="java.net.MalformedURLException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>

	<Exception name="NULL_POINTER_EXCEPTION" class="java.lang.NullPointerException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>

	<Exception name="JAVA_EXCEPTION" class="java.lang.Exception">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>





	<!-- *********************************************
	     EXCEPTION CATAGORY = 05 => Middleware Related
	     ********************************************* -->

	<Exception name="WMQ" >
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>

	<Exception name="JMS" class="java.jms.JMSException" >
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>

	<Exception name="WMB" class="com.ibm.broker.plugin.MBUserException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>


	
	
	<!-- *******************************************
	     EXCEPTION CATAGORY = 06 => Database Related
	     ******************************************* -->

	<Exception name="SQL" class="java.sql.SQLException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>




	<!-- *************************************************
	     EXCEPTION CATAGORY = 07 => User Interface Related
	     ************************************************* -->

	<Exception name="ECLIPSE_CORE_EXCEPTION" class="org.eclipse.core.runtime.CoreException">
		<Parameter name="Cause" member="getCause" type="method"/>
		<Parameter name="Message" member="getMessage" type="method"/>
	</Exception>





</exc:ExceptionCatalog>
