=== djstein/eeh_pattern/EEH_Pattern/master/schema/ExceptionCatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:exc="urn:com.ibm.mq.exc" targetNamespace="urn:com.ibm.mq.exc">
	<xsd:element name="ExceptionCatalog" type="exc:Typ.ExceptionCatalog">
		<xsd:key name="excName">
		  <xsd:selector xpath="Exception"/>
		  <xsd:field xpath="@name"/>
		</xsd:key>
		<xsd:key name="excCode">
		  <xsd:selector xpath="Exception"/>
		  <xsd:field xpath="@code"/>
		</xsd:key>
	</xsd:element>
	
	<xsd:complexType name="Typ.ExceptionCatalog">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="1" name="Exception" type="exc:Typ.Exception">
				<xsd:key name="excParm">
				  <xsd:selector xpath="Parameter"/>
				  <xsd:field xpath="@name"/>
				</xsd:key>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="version" type="xsd:string" use="required"/>
		<xsd:attribute name="appid" type="xsd:string" use="required"/>
       	<xsd:attribute name="expiry" type="xsd:int" default="604800"/>
       	<xsd:attribute name="expiredQueue" type="xsd:string" use="required"/>
       	<xsd:attribute name="descr" type="xsd:string" use="required"/>
    </xsd:complexType>
	
	<xsd:complexType name="Typ.Exception">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:string"/>
					<xsd:attribute name="descr" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="priority">
			<xsd:simpleType>
				<xsd:restriction base="xsd:int">
					<xsd:minInclusive value="1"/>
					<xsd:maxInclusive value="4"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="code" type="xsd:string"/>
		<xsd:attribute name="descr" type="xsd:string"/>
	</xsd:complexType>
	
</xsd:schema>

=== djstein/eeh_pattern/EEH_Pattern/master/exccat/ExcCat.EEH_REF.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

 Licensed Materials - Property of IBM
 (C) Copyright IBM Corp. 2009 All Rights Reserved.
 US Government Users Restricted Rights - Use, duplication or
 disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

 Created January 2008, 2012

-->

<exc:ExceptionCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="urn:com.ibm.mq.exc ExceptionCatalog.xsd"
					xmlns:exc="urn:com.ibm.mq.exc"

		name="ExcCat.EEH_REF"
		version="1.0.0"
		expiry="604800"
		expiredQueue="Q.EEH.EXPIRED"
		appid="EEH"
		descr="Internal Exception Catalog for EEH.">



	<!-- *************************************************** 
	     EXCEPTION CATAGORY = 01 => Operating System Related 
	     *************************************************** -->
	
	<Exception name="INSTALL_PATH_UNDEF" priority="3" code="91001" descr="Installation path cannot be determined!">
		<Parameter name="Key" descr="The key looked for in the environment variable."/>
	</Exception>

	<Exception name="HOST_UNKNOWN" priority="3" code="91002" descr="Host could not be deternimed!"/>

	<Exception name="FILE_NOT_FOUND" priority="3" code="91003" descr="File not found Error!">
		<Parameter name="File" descr="Filename and path of the file that could not be located."/>
	</Exception>

	<Exception name="IO" priority="3" code="91004" descr="I/O Exception generated at runtime; please refer to the exception dump!"/>

	<Exception name="CLASS_UNDEF" priority="3" code="91005" descr="Class could not be found!">
		<Parameter name="Class" descr="Class name that could not be located."/>
	</Exception>

	<Exception name="CLASS_INSTANTIATION_ERROR" priority="3" code="91006" descr="Class could not be found!">
		<Parameter name="Class" descr="Class name that could not be located."/>
	</Exception>

	<Exception name="CLASS_ATTRIBUTE_UNDEF" priority="3" code="91007" descr="Class attibute looked up by reflection could not be found!">
		<Parameter name="Class" descr="Class name."/>
		<Parameter name="Attribute" descr="Attribute name that could not be located."/>
	</Exception>

	<Exception name="CLASS_METHOD_UNDEF" priority="3" code="91008" descr="Class method looked up by reflection could not be found!">
		<Parameter name="Class" descr="Class name."/>
		<Parameter name="Method" descr="Method name that could not be located."/>
	</Exception>

	<Exception name="CLASS_ATTRIBUTE_INVOKE_ERROR" priority="3" code="91009" descr="Class attibute looked up by reflection could not be invoked!">
		<Parameter name="Class" descr="Class name."/>
		<Parameter name="Attribute" descr="Attribute name that could not be invoked."/>
	</Exception>

	<Exception name="CLASS_METHOD_INVOKE_ERROR" priority="3" code="91010" descr="Class method looked up by reflection could not be invoked!">
		<Parameter name="Class" descr="Class name."/>
		<Parameter name="Method" descr="Method name that could not be invoked."/>
	</Exception>

	<Exception name="INERRUPTED" priority="2" code="91011" descr="The thread has been interrupted!">
		<Parameter name="Message" descr="Interruption message."/>
	</Exception>






	<!-- ****************************************** 
	     EXCEPTION CATAGORY = 02 => Network Related
	     ****************************************** -->


	<!-- *******************************************
	     EXCEPTION CATAGORY = 03 => Security Related
	     ******************************************* -->

	<Exception name="FILE_SECURITY" priority="4" code="93001" descr="File or Directory is inaccessible in the path!">
		<Parameter name="Path" descr="Path specified for File or Directory."/>
	</Exception>

	<Exception name="CLASS_INACCESSIBLE" priority="4" code="93002" descr="Class accessed violates security restrictions!">
		<Parameter name="Class" descr="The class that is being accessed."/>
	</Exception>

	<Exception name="CLASS_ATTRIBUTE_INACCESSIBLE" priority="4" code="93003" descr="Class attribute accessed using reflections violates security restrictions!">
		<Parameter name="Class" descr="Class Name."/>
		<Parameter name="Attribute" descr="Attribute name that could not be accessed."/>
	</Exception>

	<Exception name="CLASS_METHOD_INACCESSIBLE" priority="4" code="93004" descr="Class method accessed using reflections violates security restrictions!">
		<Parameter name="Class" descr="Class Name."/>
		<Parameter name="Method" descr="Method name that could not be accessed."/>
	</Exception>

	<Exception name="DEF_CONSTR_INACCESSIBLE" priority="4" code="93005" descr="Default Class Constructor accessed violates security restrictions!">
		<Parameter name="Class" descr="The class that is being attempted for instantiation."/>
	</Exception>

	<Exception name="CIPHER_ALG_UNDEF" priority="4" code="93006" descr="Cipher Alogorithm provided is not supported by the provider!">
		<Parameter name="Algorithm" descr="Cipher Algorithm."/>
		<Parameter name="Message" descr="Exception Message."/>
	</Exception>

	<Exception name="CIPHER_PAD_UNDEF" priority="4" code="93007" descr="Padding with the Cipher Alogorithm provided is not supported by the provider!">
		<Parameter name="Algorithm" descr="Cipher Algorithm."/>
		<Parameter name="Message" descr="Exception Message."/>
	</Exception>

	<Exception name="CIPHER_KEY_INVALID" priority="4" code="93008" descr="The Cipher Key provided for encryption or decryption is invalid!">
		<Parameter name="Mode" descr="Cipher Mode = ENCRYPT_MODE or DECRYPT_MODE."/>
		<Parameter name="Message" descr="Exception Message."/>
	</Exception>

	<Exception name="CIPHER_BLOCK_SIZE" priority="4" code="93009" descr="The Cipher Block Size is invalid!">
		<Parameter name="Message" descr="Exception Message."/>
	</Exception>

	<Exception name="CIPHER_BAD_PAD" priority="4" code="93010" descr="The Cipher Padding is invalid!">
		<Parameter name="Message" descr="Exception Message."/>
	</Exception>




	<!-- *************************************************
	     EXCEPTION CATAGORY = 04 => Data Integrity Related
	     ************************************************* -->

	<Exception name="XML_VALIDATION" priority="3" code="94001" descr="XML Validation Error!">
		<Parameter name="SystemId" descr="System identifier of the xml file."/>
		<Parameter name="Message" descr="Reason for the XML violation to occur."/>
		<Parameter name="ColumnNo" descr="Column number where the exception occerred."/>
		<Parameter name="LineNo" descr="Line number where the exception occurred."/>
		<Parameter name="PublicId" descr="External public Identifier if one exits."/>
	</Exception>

	<Exception name="XMLNS_VALIDATION" priority="3" code="94002" descr="XMLNS Validation Error! Valid XML Namespace is 'urn:com.ibm.mq.exc'.">
		<Parameter name="InvalidXMLNS" descr="Invalid XML Namespace."/>
	</Exception>

	<Exception name="CATALOG_NULL" priority="3" code="94003" descr="Exception Catalog has not been defined!"/>

	<Exception name="CATALOG_REDEF" priority="3" code="94004" descr="Exception Catalog is being redefined!">
		<Parameter name="ExcCat" descr="Exception Catalog."/>
		<Parameter name="ExcCatVer" descr="Exception Catalog Version."/>
	</Exception>

	<Exception name="CATALOG_UNDEF" priority="3" code="94005" descr="Exception Catalog is not defined!">
		<Parameter name="CallStack" descr="Call Stack of the original Exception."/>
		<Parameter name="ExcCat" descr="Exception Catalog."/>
		<Parameter name="ExcCatVer" descr="Exception Catalog Version."/>
	</Exception>

	<Exception name="APPID_REDEF" priority="3" code="94006" descr="Application Identifier is being redefined!">
		<Parameter name="AppId_New" descr="New Application Identifier conflict."/>
		<Parameter name="AppId" descr="Application Identifier defined."/>
	</Exception>

	<Exception name="EXCEPTION_UNDEF" priority="3" code="94007" descr="Exception is not defined in the catalog!">
		<Parameter name="CallStack" descr="Call Stack of the original Exception."/>
		<Parameter name="Exc" descr="Exception not found in the catalog."/>
		<Parameter name="ExcCat" descr="Exception Catalog."/>
		<Parameter name="ExcCatVer" descr="Exception Catalog Version."/>
	</Exception>

	<Exception name="PARM_INVALID" priority="3" code="94008" descr="Exception parameter is not valid for the Exception in the catalog!">
		<Parameter name="CallStack" descr="Call Stack of the original Exception."/>
		<Parameter name="Parms" descr="Exception parameter not valid for the Exception."/>
		<Parameter name="InvalidParms" descr="Exception parameter not valid for the Exception."/>
		<Parameter name="Exc" descr="Exception found in the catalog."/>
		<Parameter name="ExcCat" descr="Exception Catalog."/>
		<Parameter name="ExcCatVer" descr="Exception Catalog Version."/>
	</Exception>

	<Exception name="QMGR_CONN_REDEF" priority="3" code="94009" descr="Queue Manager connection redefinition; one has already been defined!">
		<Parameter name="QMgr" descr="Queue Manager being redefined."/>
	</Exception>

	<Exception name="REQUEUE_NOT_SET" priority="3" code="94010" descr="Re-Queue queue name has not been defined!"/>

	<Exception name="QUEUE_NOT_SET" priority="3" code="94011" descr="Queue name has not been defined!"/>

	<Exception name="DUMP_REDEF" priority="3" code="94012" descr="Exception Dump redefinition; one has already been defined!">
		<Parameter name="DumpType" descr="The type of exception dump already set."/>
	</Exception>

	<Exception name="DUMP_UNSUPPORTED" priority="3" code="94013" descr="Exception Dump type is not supported! Supported types are binary, string, xml, java:Exception, java:DumpRenderer.">
		<Parameter name="DumpType" descr="The type of exception dump provided."/>
	</Exception>

	<Exception name="DATA_REDEF" priority="3" code="94014" descr="Data format type redefinition; one has already been defined!">
		<Parameter name="DataType" descr="The type of data format already set."/>
	</Exception>
